name: current
on:
  workflow_dispatch: {}
jobs:
  release:
    runs-on: ubuntu-latest
    environment:
      name: ${{ matrix.environment }}
    concurrency:
      group: ${{ matrix.environment }}-deploy
      cancel-in-progress: false
    steps:
      - name: Echo
        env:
          environment: ${{ matrix.environment }}
        run: echo "Deploying to $environment"
    strategy:
      max-parallel: 1
      matrix:
        include:
          - environment: Dev
          - environment: UAT
          - environment: Prod
        environment:
          - Dev
          - UAT
          - Prod
