name: current
on:
  workflow_dispatch: {}
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: read
    environment:
      name: ${{ matrix.environment }}
    concurrency:
      group: ${{ matrix.environment }}-deploy
      cancel-in-progress: false
    env:
      ENV_NAME: ${{ matrix.environment }}
    steps:
      - name: Echo
        run: echo "Deploying to $ENV_NAME"
    strategy:
      max-parallel: 1
      matrix:
        environment: [Dev, UAT, Prod]