name: current
on:
  workflow_dispatch: {}
jobs:
  release:
    runs-on: ubuntu-latest
    environment:
      name: ${{ matrix.environment }}
    concurrency:
      group: ${{ matrix.environment }}-deploy
      cancel-in-progress: false
    env:
      ENV_NAME: ${{ matrix.environment }}
    steps:
      - name: Echo
        run: echo "Deploying to $ENV_NAME"
    strategy:
      max-parallel: 1
      matrix:
        include:
          - environment: Dev
            name: Dev
          - environment: UAT
            name: UAT
          - environment: Prod
            name: Prod
