name: current
on:
  workflow_dispatch: {}
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: read
    environment:
      name: ${{ matrix.environment }}
    concurrency:
      group: ${{ matrix.environment }}-deploy
      cancel-in-progress: false
    env:
      ENV_NAME: ${{ matrix.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.sha }}
          fetch-depth: 0
    strategy:
      max-parallel: 1
      matrix:
        include:
          - environment: Dev
            name: Dev
          - environment: UAT
            name: UAT
          - environment: Prod
            name: Prod
